services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
      - ./docker/init-uuid-extension.sql:/docker-entrypoint-initdb.d/init-uuid-extension.sql
  minio:
    image: 'minio/minio'
    command: server /data --console-address ":9001"
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/minio:/data
volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
