services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
      - ./docker/init-uuid-extension.sql:/docker-entrypoint-initdb.d/init-uuid-extension.sql

volumes:
  postgres_data:
    driver: local
